import type { ExpertRule } from "./types";

export const keywordMap = {
  branches: {
    cse: ["cse", "computer science", "cs", "computer engineering"],
    it: ["it", "information technology"],
    ece: ["ece", "electronics", "communication"],
    mechanical: ["mechanical", "mech"],
    civil: ["civil"],
  },
  years: {
    "first year": ["first year", "1st year", "fy", "freshman"],
    "second year": ["second year", "2nd year", "sophomore"],
    "third year": ["third year", "3rd year", "pre final"],
    "final year": ["final year", "4th year", "last year"],
  },
  interests: {
    ai: ["ai", "a.i", "a i", "al", "artificial intelligence", "machine learning", "ml", "genai", "llm"],
    "web development": ["web", "web development", "frontend", "backend", "full stack", "fullstack", "nextjs", "react"],
    "app development": ["app development", "mobile app", "android", "ios", "flutter", "react native"],
    "data science": ["data science", "analytics", "data analysis", "visualization"],
    cybersecurity: ["cybersecurity", "security", "ethical hacking", "network security"],
    cloud: ["cloud", "aws", "azure", "devops", "deployment"],
    "ui ux": ["ui", "ux", "ui ux", "figma", "design"],
    blockchain: ["blockchain", "web3", "smart contract"],
    iot: ["iot", "internet of things", "arduino", "sensors"],
  },
  skills: {
    python: ["python"],
    javascript: ["javascript", "js", "typescript", "ts"],
    react: ["react", "nextjs", "next.js"],
    flutter: ["flutter", "dart"],
    java: ["java", "kotlin"],
    sql: ["sql", "database", "mysql", "postgres"],
    dsa: ["dsa", "data structures", "algorithms"],
    ml: ["ml", "machine learning", "scikit", "tensorflow", "pytorch"],
    communication: ["communication", "presentation", "english"],
  },
  goals: {
    project: ["project", "mini project", "major project", "build", "prototype"],
    internship: ["internship", "intern", "industrial training"],
    placement: ["placement", "job", "career", "package"],
    "higher studies": ["higher studies", "masters", "gate", "gre"],
    startup: ["startup", "business", "entrepreneurship"],
  },
  emotions: {
    confused: ["confused", "not sure", "unsure", "doubt", "stuck", "lost", "what should"],
    stressed: ["stress", "stressed", "worried", "pressure", "anxious", "panic", "scared"],
    confident: ["confident", "ready", "sure", "clear", "decided"],
  },
} as const;

export const expertRules: ExpertRule[] = [
  {
    id: "R1",
    name: "AI project fit",
    description: "AI interest with project goal maps to an applied AI build.",
    condition: { interests: ["ai"], goals: ["project"] },
    recommendation: "Build an AI-powered student assistant with a rule engine and visual explanation graph.",
    category: "AI Project Track",
    weight: 0.86,
  },
  {
    id: "R2",
    name: "Full-stack project fit",
    description: "Web development interest with project goal maps to a deployable full-stack project.",
    condition: { interests: ["web development"], goals: ["project"] },
    recommendation: "Build a full-stack portfolio project using Next.js, API routes, and a clean interactive UI.",
    category: "Full Stack Project Track",
    weight: 0.8,
  },
  {
    id: "R3",
    name: "AI plus web combination",
    description: "AI and web development together are strongest as a browser-based intelligent system.",
    condition: { interests: ["ai", "web development"] },
    recommendation: "Build an AI + full-stack expert system that demonstrates NLP, rules, confidence, and graph reasoning.",
    category: "AI + Full Stack Project Track",
    weight: 0.94,
  },
  {
    id: "R4",
    name: "Placement data track",
    description: "Data science with placement goal maps to interview-ready analytics preparation.",
    condition: { interests: ["data science"], goals: ["placement"] },
    recommendation: "Follow a Data Science Placement Track with Python, SQL, dashboards, and case-study projects.",
    category: "Data Science Placement Track",
    weight: 0.84,
  },
  {
    id: "R5",
    name: "Internship starter roadmap",
    description: "Internship goal with early-year status maps to fundamentals and small proof projects.",
    condition: { years: ["first year", "second year"], goals: ["internship"] },
    recommendation: "Prepare for internships with one core skill, one small project, GitHub cleanup, and a concise resume.",
    category: "Internship Preparation Track",
    weight: 0.78,
  },
  {
    id: "R6",
    name: "Frontend design portfolio",
    description: "UI/UX and web signals map to a frontend portfolio path.",
    condition: { interests: ["ui ux", "web development"] },
    recommendation: "Create a UI/UX-focused frontend portfolio with three polished case-study pages.",
    category: "Frontend/UI UX Portfolio Track",
    weight: 0.82,
  },
  {
    id: "R7",
    name: "Cybersecurity project fit",
    description: "Cybersecurity interest with project goal maps to a safe, educational security dashboard.",
    condition: { interests: ["cybersecurity"], goals: ["project"] },
    recommendation: "Build a cybersecurity awareness dashboard with phishing checks, password scoring, and learning modules.",
    category: "Cybersecurity Project Track",
    weight: 0.79,
  },
  {
    id: "R8",
    name: "Cloud deployment boost",
    description: "Cloud interest improves recommendations that involve deployment and portfolio credibility.",
    condition: { interests: ["cloud"] },
    recommendation: "Add deployment, monitoring, and documentation to make your project portfolio-ready.",
    category: "Cloud Portfolio Add-on",
    weight: 0.62,
  },
  {
    id: "R9",
    name: "Confusion support",
    description: "Confused students need a narrowed recommendation with concrete next actions.",
    condition: { emotion: ["confused"] },
    recommendation: "Choose one primary track now and use a three-step plan instead of comparing every option.",
    category: "Decision Support",
    weight: 0.56,
  },
  {
    id: "R10",
    name: "Placement fundamentals",
    description: "Placement goal with DSA skill or CSE/IT branch maps to interview fundamentals.",
    condition: { branches: ["cse", "it"], goals: ["placement"] },
    recommendation: "Prioritize DSA, core CS basics, resume projects, and mock interviews for placement readiness.",
    category: "Software Placement Track",
    weight: 0.81,
  },
  {
    id: "R11",
    name: "Mobile app project fit",
    description: "App development with project goal maps to a student mobile app prototype.",
    condition: { interests: ["app development"], goals: ["project"] },
    recommendation: "Build a student utility mobile app such as attendance tracking, campus events, or study reminders.",
    category: "Mobile App Development Track",
    weight: 0.82,
  },
  {
    id: "R12",
    name: "ML skill project fit",
    description: "ML skill with AI interest maps to a compact machine-learning project.",
    condition: { interests: ["ai"], skills: ["ml"] },
    recommendation: "Build a machine-learning mini app with a clean UI, a small dataset, and visible model confidence.",
    category: "Machine Learning App Track",
    weight: 0.85,
  },
  {
    id: "R13",
    name: "Blockchain academic fit",
    description: "Blockchain interest maps to a safe academic proof-of-concept project.",
    condition: { interests: ["blockchain"], goals: ["project"] },
    recommendation: "Build a certificate verification or student achievement ledger using a simple blockchain concept.",
    category: "Blockchain Academic Track",
    weight: 0.74,
  },
  {
    id: "R14",
    name: "IoT campus fit",
    description: "IoT interest maps to a campus-focused sensor dashboard.",
    condition: { interests: ["iot"], goals: ["project"] },
    recommendation: "Build an IoT campus monitoring dashboard for room occupancy, energy use, or smart lab alerts.",
    category: "IoT Campus Project Track",
    weight: 0.77,
  },
  {
    id: "R15",
    name: "Final-year project pressure",
    description: "Final-year students need a project with visible output and clear documentation.",
    condition: { years: ["final year"], goals: ["project"] },
    recommendation: "Pick a project with visible UI, explanation, deployment, and a clear report structure.",
    category: "Final Year Project Track",
    weight: 0.76,
  },
  {
    id: "R16",
    name: "App internship fit",
    description: "App development with internship goal maps to portfolio-ready mobile skills.",
    condition: { interests: ["app development"], goals: ["internship"] },
    recommendation: "Prepare an app-development internship portfolio with one polished Flutter or React Native project.",
    category: "App Development Internship Track",
    weight: 0.8,
  },
];
